version: "3.8"

services:
  book_manager_database:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_db
    networks:
      - book_manager_network
    ports:
      - 5432:5432

networks:
  book_manager_network: